### ISSUE TITLE
Adding new vulnerabilities

### ISSUE THREAD

**Issue by mdhash** [omererdem/honeything#2]
I would like to contribute on adding support for latest TR-069 vulnerabilities. I went through the source code but could not figure out the exact working. Any help will be appreciated.

**Comment by omererdem** [comment]
Thanks for your interest! 

HoneyThing consists of two main components: TR-069 protocol and vulnerabilities. Other than implementing TR-069 protocol from scratch, we incorporated an open source TR-069 implementation ([Catawampus](https://github.com/omererdem/honeything/tree/master/src/cwmp)). RomPager embedded web server emulation part includes vulnerability codes. But, the current code is base and requires some reworking to make it more generic and modular. Then, it will be easier to add new vulnerability modules.

We're planning to improve HoneyThing capabilities this year at GSoC. If you're eligible and would like to apply as a GSoC student, follow the steps at [Honeynet Project website](https://www.honeynet.org/gsoc2017/ideas). On the other hand, all contribution you want to make will be welcome.
